#
#  The parsing script will build an 'N-Tuple' from each
#  PROTECTED_PARENT variable.
#
# Recognized variable/value pairs are:
#   These are for debugging and subversion
#          DEBUG                = N
#          SVNPATH              = path to svn
#          SVNLOOK              = path to svnlook
#   These make up an N-Tuple
#          PROTECTED_PARENT             = /<path>
#    e.g.: PROTECTED_PRJDIRS    = /<path>/*
# or e.g.: PROTECTED_PRJDIRS    = /<path>/*/*
#          PRJDIR_CREATORS      = '*' or '<user>, <user>, ...'
#          ARCHIVE_DIRECTORY    = <name>

### These should be first
DEBUG             = 0
SVNPATH           = "/usr/bin/svn"
SVNLOOK           = "/usr/bin/svnlook"

### These comprise an N-Tuple, can be repeated as many times as wanted,
### but each PROTECTED_PARENT value must be unique.   It is not allowed to
### try to configure the same directory twice (or more)!
PROTECTED_PARENT  = "/tags"
PROTECTED_PRJDIRS = "/tags/*"
PRJDIR_CREATORS   = "*"
ARCHIVE_DIRECTORY = "Archive"
