#! /usr/bin/perl -w

#
#  Copyright 2015,2016,2017 Joseph C. Pietras
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

use warnings;
use strict;
use SVNPlus::TagProtect;

$_ = $0;
s@.*/@@;
my $NAME = $_;

# build the object: it exits if args are invalid
my $tagprotect = SVNPlus::TagProtect->new( $0, \@ARGV );

if ( $tagprotect->SimplyAllow() )
{

    # if the commit is ok, because it does impact protected directories,
    # but debug is wanted then this script must exit NON-zero, which
    # causes the commit to fail but the client gets the standard error.
    # A zero exit causes the STDERR to be squashed.  If any "True"
    # errors occured, "SimplyAllow" will have printed them to standard
    # error and would have returned 0.
    if ( $tagprotect->GetDebugLevel > 0 )
    {
        print STDERR
            "$NAME: SimplyAllow succeeded but script exiting 1 (FAIL) because debug is enabled.\n";
        exit 1;
    }
    exit 0;
}

if ( $tagprotect->AllowCommit() )
{

    # if the commit is ok, i.e.: it is allowed, but debug is wanted
    # then this script must exit NON-zero, which causes the commit to
    # fail but the client gets the standard error.  A zero exit causes
    # the STDERR to be squashed.    If any "True" errors occurred,
    # "AllowCommit" will have printed them to standard error and would
    # have returned 0.
    if ( $tagprotect->GetDebugLevel > 0 )
    {
        print STDERR
            "$NAME: AllowCommit succeeded but script exiting 1 (FAIL) because debug is enabled.\n";
        exit 1;
    }
    exit 0;
}

# commit is not allowed, sub "AllowCommit" has already output the reason
print STDERR "$NAME: exit 1 (FAIL) this is a true prevent commit condition.\n"
  if ( $tagprotect->GetDebugLevel > 0 );
exit 1;
