#! /bin/bash -norc
set -u
NAME=${0##*/};
DIRE=${0%/*}; if [[ -z "${DIRE}" ]]; then DIRE="."; fi;
              if [[ "${DIRE}" = "${NAME}" ]]; then DIRE="."; fi;
DIRE="$(cd ${DIRE}; echo ${PWD})";
TAB='	'; # must be a TAB not a run of spaces
unset CDPATH; # because when bash (I love it!) is involved, CDPATH can hose up a subshell/make, etc.
unset BASH_ENV;
unset ENV;       # unset the ENV environmental variable so any
                 # Korn shells below this line do not attempt to
                 # source it. Ditto for BASH_ENV
# the environment variable
#    ECHO
# is examined, if it is TRUE/YES/ON (case insensitve)
# then turn on shell debugging
case ${ECHO:-null} in
     [Tt][Rr][Uu][Ee] ) set -x ;;
     [Yy][Ee][Ss]     ) set -x ;;
     [Oo][Nn]         ) set -x ;;
esac

# create a suite of temp files and then functions to clean them up
TDIR=${TMPDIR:-/tmp}; # why examine TMPDIR? see tmpnam(3), but DO NOT export TDIR
T0=${TDIR}/${NAME}-$$-0;
T1=${TDIR}/${NAME}-$$-1;
T2=${TDIR}/${NAME}-$$-2;
T3=${TDIR}/${NAME}-$$-3;
T4=${TDIR}/${NAME}-$$-4;
T5=${TDIR}/${NAME}-$$-5;
T6=${TDIR}/${NAME}-$$-6;
T7=${TDIR}/${NAME}-$$-7;
T8=${TDIR}/${NAME}-$$-8;
T9=${TDIR}/${NAME}-$$-9;

# create helper functions for the "trap" command
function RmTmps { # usage: RmTmps - will clear all the tmp files
    /bin/rm -f ${T0} ${T1} ${T2} ${T3} ${T4} ${T5} ${T6} ${T7} ${T8} ${T9}
}

# this function will clean up temp files then exit
function Exit { # usage: Exit N (N defaults to zero (0))
    __evalue=${?}; # grab the most recent exit status
    RmTmps;
    if   (( ${#} ==  0  )); then
            exit ${__evalue};
    else
            exit ${1};
    fi
}

function EError { Error "${@}"; Exit 1; }
function Error  { oV=${VERBOSE}; VERBOSE=1; Verbose ${@} VERBOSE=${oV}; }

function Verbose {
    if (( VERBOSE > 0 )); then
        (
            _n='';
            if (( ${#} > 0 )); then
               if [[ "${1}" = "-n" ]]; then _n=-n; fi;
               echo ${_n} ${NAME}: "${@}";
            else
               echo '';
            fi;
        ) 1>&2;
    fi;
}

trap "Exit 2" 1 2 15; # exit if hit with HUP, INT or TERM signals, you can extend this list
if (( ${#} == 0)); then set -- --help; fi;

let DEF_VERBOSE=1 || true; let VERBOSE=1 || true;
let DEF_CLEAN=1   || true; let CLEAN=1 || true;
let DEF_XLEAN=1   || true; let XLEAN=1 || true;
    DEF_VERSION="";            VERSION="";

if [[ ${OSTYPE} =~ darwin* ]]; then
    KILLDIR="/Library/Python/2.7/site-packages";
else
    KILLDIR="/usr/lib/python2.7/site-packages";
fi;
GOTO="${DIRE}/../tagProtect";
DEF_TARDIR="${GOTO}/PERL-Object"
DEF_TARDIR="$(cd ${DEF_TARDIR} 2>/dev/null;  echo ${PWD})";

USAGE="
usage: ${NAME} [options]

   locally installs/reinstalls svnPlus
";

while (( ${#} > 0 )); do
    case "${1}" in # (((((((((((((((((
        --help      | -h    ) echo "${USAGE}"; exit 0;;
        --run       | -r | -) : ;; # ignore it
        --clean     | -c    ) let CLEAN=1 || true;;
        --noclean   | -C    ) let CLEAN=0 || true;;
        --no-clean          ) let CLEAN=0 || true;;
        --extra*    | -e    ) let XLEAN=1 || true;;
        --x*        | -x    ) let XLEAN=1 || true;;
        --noextra*  | -E    ) let XLEAN=0 || true;;
        --no-extra*         ) let XLEAN=0 || true;;
                      -X    ) let XLEAN=1 || true;;
        --verbose   | -v    ) if (( VERBOSE <= 0 )); then let VERBOSE=1 || true; else let VERBOSE++ || true; fi;;
        --verbose=0         ) let VERBOSE=0 || true;;
        --verbose=[1-9]*    ) let VERBOSE=${1#--verbose=} || exit 1;;
        --v0                ) let VERBOSE=0 || true;;
        --v[1-9]*           ) let VERBOSE=${1#-v} || exit 1;;
        --noverbose | -V    ) let VERBOSE=0 || true;;
                           *) echo "${NAME}: arg \"${1}\" unrecognized, aborting!" 1>&2; Exit 1;;
    esac;
    shift; # off the one just done
done

if (( VERBOSE    < 0 )); then let VERBOSE=${DEF_VERBOSE} || true; fi;
if (( CLEAN      < 0 )); then let CLEAN=${DEF_CLEAN}     || true; fi;
if (( XLEAN      < 0 )); then let XLEAN=${DEF_XLEAN}     || true; fi;
if [[ "${TARDIR:-not set}" = "not set" ]]; then TARDIR="${DEF_TARDIR}"; fi;
cd "${TARDIR}" || {
     Error ${NAME}: current directory is ${PWD};
    EError ${NAME}: failed to cd to ${TARDIR};
}

looping=1;

while (( looping > 0 )); do
    V_Changes="$(sed -n -e '/^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*[ '"${TAB}"']/{' \
           -e '   s@[ '"${TAB}"'].*@@p' \
           -e '   q' \
           -e '}' Changes)" || exit 1;
    if [[ -z "${V_Changes}" ]]; then
         VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed to get version from file Changes; exit 1;
    fi;
    V_TagProtect="$(egrep 'our[ '"${TAB}"']*\$VERSION' lib/SVNPlus/TagProtect.pm | sed -e 's@.*=@@' -e 's@"@@g' -e "s@'@@g" -e 's@;@@g' -e 's@[ '"${TAB}"']*@@g';)" || exit 1;
    if [[ -z "${V_TagProtect}" ]]; then
         VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed to get version from file lib/SVNPlus/TagProtect; exit 1;
    fi;
    V_README="$(sed -n -e '1,1 {' \
           -e '   s@.*[ '"${TAB}"']@@p' \
           -e '   q' \
           -e '}' README.md)" || exit 1;
    if [[ -z "${V_README}" ]]; then
         VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed to get version from file README.md; exit 1;
    fi;
    if [[ "${V_Changes}" != "${V_TagProtect}" || "${V_Changes}" != "${V_README}" ]]; then
         VERBOSE=1; Verbose pwd=$(/bin/pwd -P);
         Verbose "version numbers do not all match";
         Verbose From file \"Changes\" ${V_Changes};
         Verbose From file \"lib/SVNPLus/TagProtect\" ${V_TagProtect};
         Verbose From file \"README.md\" ${V_README};
         exit 1;
    fi;
    Verbose version is ${V_Changes};
    read -p "${NAME}: version ${V_Changes}, edit? (y/N) " ans ;
    if [[ "${ans:-not set}" = "not set" ]]; then ans=n; fi;
    case ${ans} in # ((
        n*|N*) looping=0 ;;
        q*|Q*) echo ${NAME}: exiting 1>&2; exit 0;;
         *   ) vi Changes lib/SVNPlus/TagProtect.pm README.md;;
    esac;
done

Verbose perl Makefile.PL ; perl Makefile.PL  || {
     VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed command perl Makefile.PL; exit 1;
}
Verbose make             ; make              || {
     VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed command make            ; exit 1;
}
Verbose make test        ; make test         || {
     VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed command make test       ; exit 1;
}
Verbose sudo make install; sudo make install || {
     VERBOSE=1; Verbose pwd=$(/bin/pwd -P); Verbose failed command sudo make install; exit 1;
}

if (( CLEAN )); then
    Verbose /bin/rm -rf  MYMETA.json MYMETA.yml Makefile blib/ pm_to_blib
            /bin/rm -rf  MYMETA.json MYMETA.yml Makefile blib/ pm_to_blib
fi;
